export const routes = {
  main: '/',
  posts: '/posts',
  aboutUs: '/aboutUs',
  gallery: '/gallery',
  video: '/video',
  post1: '/posts/post1',
  post2: '/posts/post2',
  post3: '/posts/post3',
  post4: '/posts/post4',
  post5: '/posts/post5',
  post6: '/posts/post6',
  auth: '/auth',
  notFound: '*',
};
